# file: tasks/el7.yml
---
- name: Checking current git version
  ansible.builtin.shell: |
    set -o pipefail
    git --version | cut -d ' ' -f 3
  args:
    executable: /bin/bash
  changed_when: false
  register: gitcheck
  ignore_errors: true

- name: Displaying current git version
  ansible.builtin.debug:
    msg: |
      {%- if gitcheck.failed -%}
      Git is not installed
      {%- else -%}
      Found git version {{ gitcheck.stdout }}
      {%- endif -%}

- name: Uninstalling old git
  ansible.builtin.yum:
    name: git-{{ gitcheck.stdout }}
    state: absent
    autoremove: true
  when: gitcheck.stdout is search('1.8')

- name: Adding the IUS CentOS 7 repo
  ansible.builtin.yum:
    name: https://repo.ius.io/ius-release-el7.rpm
    state: installed

- name: Installing git2
  ansible.builtin.yum:
    name: git236-all
    state: installed

- name: Installing git-lfs
  ansible.builtin.yum:
    name: git-lfs
    state: installed
...
